### ISSUE TITLE
Feature Request - simple PHP 8.1 support addition

### ISSUE THREAD

**Issue by obj63mc** [jgivoni/flysystem-cache-adapter#1]
Testing your code base on some sites and looking to utilize this with our module https://github.com/silverstripe/silverstripe-s3 - we would like to see if we can add php8.1 support to this module.

Currently the only thing preventing that is the use of constants in your trait CacheItemsTrait - https://github.com/jgivoni/flysystem-cache-adapter/blob/master/src/CacheItemsTrait.php#L21

    const CACHE_KEY_PREFIX = 'flysystem_item_';
    const CACHE_KEY_HASH_SALT = '563ce5132194441b';

And then on https://github.com/jgivoni/flysystem-cache-adapter/blob/master/src/CacheItemsTrait.php#L64

    return self::CACHE_KEY_PREFIX . md5(self::CACHE_KEY_HASH_SALT . $path);

If we simply set these as a static for now or hard coded them everything works fine with php 8.1.

Willing to submit a PR as well

**Comment by jgivoni** [comment]
Ok, interesting, Joseph. Thanks for submitting, I will look into it. Sorry I didn't respond before, I didn't get any notification from Github on the opening of an issue nor PR.

**Comment by jgivoni** [comment]
Accepted, thanks for helping with this!
Latest version: 3.0.3
